server:
  port: 8081

# -- Default spring configuration
spring:
  application:
    name: user

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddib?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: adkafjlsdjgldkfjskdlakjdjkfljdkjkdkkkksjakslfejfghlajsdflaksjdgljadk

  profiles:
    include: oauth

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 793763532683-d9v2q5c00cqum388s5emgpn2m9tmf5ek.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8084/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
access:
  token:
    expiration:
      time: 3600000

refresh:
  token:
    expiration:
      time: 864000000

releaseHostName: localhost

# -- Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}
