server:
  port: 8000

# -- Default spring configuration
spring:
  application:
    name: gateway

# -- Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}